name: doctors_path_academy
description: "A new Flutter project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  firebase_messaging: ^14.9.4
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  device_info_plus: ^10.1.2
  video_player: ^2.8.0
  chewie: ^1.8.0
  connectivity_plus: ^6.0.3
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  firebase_app_check: ^0.2.2+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "legacy"
  ios: true
  image_path: "assets/logo.png"

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/logo.png
  android: true
  ios: true
